package ru.itis.summerpractice24.hm2

object CarRepository {

    val cars: List<Car> = listOf(
        Car(
            id = 0,
            name = "McLaren 570S, 2021",
            price = "$191,100",
            url = "https://i0.wp.com/practicalmotoring.com.au/wp-content/uploads/2015/03/980722_03_McLaren-570S_NYlaunch.jpg?w=2048&ssl=1",
            secondUrl = "https://www.velocityjournal.com/images/stk/2018/728/ml2018570sspider72887064_1200.jpg",
            zeroToHundred = "0-100: 3.2 seconds",
            topSpeed = "Top speed: 328 km/h",
            description = "All the driving characteristics of the Coupe, plus the added exhilaration of open-top driving. The 570S Spider brings you closer to every aspect of its design, which is equally stunning with the roof up or down.",
        ),
        Car(
            id = 1,
            name = "Tesla Model 3 Highland, 2024",
            price = "$47,490",
            url = "https://www.electrive.com/media/2023/09/tesla-model-3-highland-2023-10-min-1400x700.jpg",
            secondUrl = "https://foto.carexpert.ru/img/foto1680/tesla/teslm3027.jpg",
            zeroToHundred = "0-100: 6.1 seconds",
            topSpeed = "Top speed: 201 km/h",
            description = "Model 3 benefits from the same features that make our other vehicles so safe. Active safety features like automatic emergency braking come standard.",
        ),
        Car(
            id = 2,
            name = "Ferrari Portofino, 2022",
            price = "$230,950",
            url = "https://www.automotorsport.com.tr/wp-content/uploads/2018/02/Ferrari-Portofino.jpg",
            secondUrl = "https://images.drive.ru/i/0/5f6222f3ec05c40919000027.jpeg",
            zeroToHundred = "0-100: 3.45 seconds",
            topSpeed = "Top speed: 320 km/h",
            description = "The Ferrari Portofino is the new V8 Gran Turismo, designed to win the hearts of the segment's car enthusiasts with the perfect combination of outstanding performance and versatility, delivering supreme driving pleasure and unparalleled ride comfort.",
        ),
        Car(
            id = 3,
            name = "Bugatti Chiron, 2022",
            price = "$3,300,000",
            url = "https://netizensreport.com/wp-content/uploads/2023/02/se-image-ea445e45baad6c053b6eabf75dbb594e.jpg",
            secondUrl = "https://s0.rbk.ru/v6_top_pics/media/img/0/94/756232195327940.jpg",
            zeroToHundred = "0-100: 2.3 seconds",
            topSpeed = "Top speed: 350 km/h",
            description = "The Bugatti Chiron is a two-seat mid-engined sports car designed and developed in Germany by Bugatti Engineering GmbH and manufactured in Molsheim, France by French automobile manufacturer Bugatti Automobiles S.A.S.",
        ),
        Car(
            id = 4,
            name = "Lamborghini Huracan, 2024",
            price = " $249,865",
            url = "https://ymimg1.b8cdn.com/uploads/car_model/4781/pictures/4023693/02.jpg",
            secondUrl = "https://smart-phoneprice.com/wp-content/uploads/2022/12/Lamborghini-Huracan-2-1024x575.jpg",
            zeroToHundred = "0-100: 3.4 seconds",
            topSpeed = "Top speed: 260 km/h",
            description = "We know what perfection is. This is how the first Lamborghini Huracan model was created. The Huracan is equipped with a powerful V10 engine and the most advanced technologies aimed at maximum performance. ",
        ),
        Car(
            id = 5,
            name = "Porsche 911 GT3 RS, 2024",
            price = "$241,300",
            url = "https://news.dupontregistry.com/wp-content/uploads/2018/02/guards_red_2019_911_gt3_rs-3.jpg",
            secondUrl = "https://foto.carexpert.ru/img/foto1680/porsche/pors91002.jpg",
            zeroToHundred = "0-100: 3.2 seconds",
            topSpeed = "Top speed: 312 km/h",
            description = "Athletes know that achieving the best results requires more than just perfect conditions and luck. The decisive factor is the unconditional desire to become faster and stronger with each training session. ",
        ),
        Car(
            id = 6,
            name = "Koenigsegg Jesko, 2021",
            price = "$3,000,000",
            url = "https://cimg2.ibsrv.net/ibimg/hgm/1024x576-1/100/694/koenigsegg-jesko_100694318.jpg",
            secondUrl = "https://i.artfile.ru/2560x1600_1547117_[www.ArtFile.ru].jpg",
            zeroToHundred = "0-100: 2.6 seconds",
            topSpeed = "Top speed: 421 km/h",
            description = "The Koenigsegg Jesko is a limited production mid-engine sports car produced by the Swedish automobile manufacturer Koenigsegg. The car was introduced at the 2019 Geneva Motor Show and was completely sold out before the show ended.",
        ),
        Car(
            id = 7,
            name = "C8 Chevrolet Corvette, 2024",
            price = "$69,995",
            url = "https://images.hgmsites.net/lrg/2017-chevrolet-corvette-2-door-grand-sport-coupe-w-2lt-side-exterior-view_100583560_l.jpg",
            secondUrl = "https://i.trse.ru/2023/01/8AyH.jpg",
            zeroToHundred = "0-100: 2.9 seconds",
            topSpeed = "Top speed: 344 km/h",
            description = "Chevrolet Corvette C8 is the eighth generation of the legendary sports model from General Motors. The car was presented to the general public at the end of July 2019 at the special exhibition.",
        ),
        Car(
            id = 8,
            name = "Tesla Cybertruck Rear-Wheel Drive, 2025",
            price = "$57,390",
            url = "https://w.wallha.com/ws/13/qr6PWmBY.jpg",
            secondUrl = "https://carsweek.ru/upload/iblock/97a/97a2af76320a70e23809732f7305f091.jpg",
            zeroToHundred = "0-100: 6.5 seconds",
            topSpeed = "Top speed: 210 km/h",
            description = "Built for any adventure, Cybertruck has a durable exterior, spacious interior and technological capabilities so you can pack up your gear and hit the road.",
        ),
        Car(
            id = 9,
            name = "Maserati MC20, 2023",
            price = "$265,195",
            url = "https://www.carpixel.net/w/e14c2766360879f668bec5ea93e5d6c4/maserati-mc20-by-novitec-wallpaper-hd-116406.jpg",
            secondUrl = "https://a.d-cd.net/nZVDU-C24859XNQZ23DhTVvUqMo-1920.jpg",
            zeroToHundred = "0-100: 2.9 seconds",
            topSpeed = "Top speed: 325 km/h",
            description = "The Maserati MC20 supercar represents a completely new era in automotive design and cutting-edge technology. Powerful, luxurious, safe and phenomenally dynamic, the MC20 defies time, making a bold leap into a bright future!",
        )

    )
}